//"use client"; //클라이언트단에서만 use활용할 수 있다. 
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
// import { useEffect, useState } from "react";

/*
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
*/

export const metadata = {
  title: "Web tutorials",
  description: "Generated by Green",
}; //서버단에만 작동한다. 

export default async function RootLayout({ children }) {

  /*
  const [topics, setTopics] = useState([]);
  useEffect(()=>{ //result -> topics 에 저장됨
    fetch('http://localhost:9999/topics')
    .then(res=>{
    return res.json(); //json형태를 object 제이쿼리 형태로 바꿈. 
    })
    .then(result=>{
     setTopics(result);
    });
  },[])
  console.log(topics);

  패치로 결과 나오면 토픽스에 담는다. 
  결과가 나올 때 까지 기다리는 함수 await 함수 (async -> 부모에 넣는다. )
  await부모는 function
  */

  const response = await fetch('http://localhost:9999/topics'); //기다리는 함수
  const topics = await response.json(); //json->object / 

  return (
    <html lang="en">
      {/* <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body> */}
      <body>
      <h1>
        <Image src="/home_google_icon.png" alt="home icon" width={48} height={48}></Image>
        <Link href="/">WEB</Link>
      </h1>
        <nav>
          <ol>
            {
             topics.map(topic=><li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>)
            }
            {/* <li><Link href="/read/1">html</Link></li>
            <li><Link href="/read/2">css</Link></li>
            <li><Link href="/read/3">javascript</Link></li> 
            let listHTML = list.map(l=> <li key={l.id}><a href={l.id}>{l.title}</a></li>);
            */}
          </ol>
        </nav>
     {children}
      <ul>
        <li><Link href="/create">Create</Link></li>
        <li><Link href="/update/1">Update</Link></li>
        <li><button>delete</button></li>
      </ul>
      </body>
    </html>
  );
}
